- name: Download the large files needed by the installer
  hosts: localhost
  vars:
    gen_dir: ./generated
    ocp_release: 4.6.31
    #rhcos_release: 4.6.1                # refer to https://mirror.openshift.com/pub/openshift-v4/dependencies/rhcos/
    rhcos_base: "{{ ocp_release | regex_search('[0-9]{1,2}\\.[0-9]{1,2}') }}"
    rhcos_url: "https://mirror.openshift.com/pub/openshift-v4/dependencies/rhcos/{{ rhcos_base }}/latest"
    prereq_list:
    - https://mirror.openshift.com/pub/openshift-v4/clients/oc/latest/linux/oc.tar.gz
    - https://releases.ubuntu.com/20.04/ubuntu-20.04.3-live-server-amd64.iso
    - "{{ rhcos_url }}/rhcos-installer-kernel-x86_64"
    - "{{ rhcos_url }}/rhcos-installer-initramfs.x86_64.img"
    - "{{ rhcos_url }}/rhcos-metal.x86_64.raw.gz"
  tasks:
  - name: Create {{ gen_dir }} if it doesn't exists
    file:
      path: "{{ gen_dir }}"
      state: directory
      
  - name: Download files
    get_url:
      url: "{{ item }}"
      dest: "{{ gen_dir }}/{{ item | basename }}"
    loop: "{{ prereq_list }}"