---
- name: install with default
  hosts: localhost
  vars_files:
  - vars/all-vars
  tasks:
  - name: Setup network
    import_role:
      name: kelvinlnx.virt_net_setup

  - name: Setup VM
    import_role:
      name: kelvinlnx.okd_vm_setup

  - meta: refresh_inventory
  
  - name: Generate Certs
    import_role:
      name: kelvinlnx.gen_certs

- name: run on registry
  hosts: registry_host
  remote_user: root
  vars_files:
  - vars/all-vars
  tasks:
  - name: Mirror OpenShift Registry
    import_role:
      name: kelvinlnx.okd_mirror

- name: final cluster setup
  hosts: localhost
  vars_files:
  - vars/all-vars
  tasks:
  - name: Install Cluster
    import_role:
      name: kelvinlnx.okd_setup
...