---
#
# If you need to make changes, just duplicate defaults/main.yml
# into your project vars folder and include it in vars_files.
#
- hosts: localhost
  # remote_user: root
  vars:
    virt_registry_remove: False
  roles:
    - kelvinlnx.okd_vm_setup
    # - role: kelvinlnx.okd_vm_setup
    #   user_pubkey_filename: "id_rsa.pub"
    #   os_iso: "/home/myuser/Downloads/ubuntu-20.04.3-live-server-amd64.iso"
    #   virt_net_name: openshift
    #   virt_net_domain: example.net
    #   vm_name: registry
    # - { role: kelvinlnx.okd_vm_setup, virt_registry_remove: True }
    