# Status of destroy and undefine doesn't change even when done
# Therefore the status settings
- block:
  - name: "CONFIG: Destroy {{ virt_net_name }}"
    virt_net:
      name: "{{ virt_net_name }}"
      command: destroy
    changed_when: true
  
  - name: "CONFIG: Undefine {{ virt_net_name }}"
    virt_net:
      name: "{{ virt_net_name }}"
      command: undefine
    changed_when: true
  rescue:
  - name: Info
    debug:
      msg: "{{ virt_net_name }} doesn't exists" 

- name: "CONFIG: Remove dns hosts file"
  file:
    path: "{{ item }}"
    state: absent
  become: true
  loop:
  - /usr/local/etc/domains/{{ virt_net_domain }}
  - /etc/NetworkManager/dispatcher.d/99-{{ virt_net_name }}.sh
