---
# defaults file for kelvinlnx.okd_setup
okd_installer: ~/Downloads/openshift-install
virt_net_name: okd
virt_net_domain: example.com
master_nodes: 3                 # do not change, rhocp only supports 3
worker_nodes: 0
ca_crt: "{{ gen_dir }}/private/myca.{{ virt_net_domain }}.crt"

gen_dir: ./generated
registry_name: myreg.{{ virt_net_domain }}
registry_user_info: 'reguser:regpass'
registry_user_email: user@{{ virt_net_domain }}