---
# tasks file for kelvinlnx.okd_vm_setup
- name: "PREREQ: Check prereq"
  import_tasks: check_prereq.yml
  
- name: "VM: Create the virtual machine {{ myvm.name }}"
  include_tasks: vm_create.yml
  when: not virt_registry_remove | bool

- name: "VM: Remove the virtual machine {{ myvm.name }}"
  include_tasks: vm_remove.yml
  when: virt_registry_remove | bool