---
# defaults file for kelvinlnx.okd_registry

gen_dir: ./generated
virt_registry_remove: False

# variable also used by virt_net_setup role
virt_net_name: okd
virt_net_domain: example.com

# The location of the ubuntu iso
os_iso: ~/Downloads/ubuntu-20.04.3-live-server-amd64.iso

myvm:
  host_ip: 88                             # only the host portion
  name: myreg
  fqdn: myreg.{{ virt_net_domain }}
  memory: 1024
  vcpu: 1
  disk:                                   # the following 3 lines used by create vm disk
    path: /var/lib/libvirt/images/myreg.qcow2
    size: 25G                             # 4.6.31 repo uses approx 6GB
  username: user
  password: password
  authorized_key: ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQDEPmLw/RI0/S7FQh8o+JXFGqh3bTX24tigDyvLg0zCcGDdWgjU7lGq+TlYUbJ3W6SFzxXUXdl1iSssEY2iw1YvwySdQgAXfBd9Hn/k/INcKEErz/A7A2z2EDP9MQHv952lAs/Uik3tA+iFyjt5C1zkeRw0r2w/BRR2vFA7CHZEd9LP/KeX1Q2OUhUIrlnfsgN5us5jB0OtKX4JR3Pf5qaBSnySsojBGbaawrWUr9wqJH2LtkoOvIj8De/jJS6LK8tBH6FV+DY3OueBqdxOtvjFHy5l1PnlWWnIFVi3qhsXIVr46CGntvpSeod6rrQhLfQ/b191/zVqSMFKAL05HTfcr4aIUOw8A4fCigypm4NmfbSq+Mhm9o19k0Dr6Zihh2za54RwZdQOoc1qQYkc19BoPFtuh7wreh4YV6m5Ir7yVt9ApoK+Xj7fYrtkk2y4jBYYm8NP41VLABY6auwTk8X5n8Y8n3RWd/IuiCETSWPivV5es3MleuMBm8AWwQ1X9f0= dops@testdesktop
