---
# tasks file for kelvinlnx.virt_setup
- name: "NET: Create the virtual network {{ virt_net_name }}"
  include_tasks: virt_net_create.yml
  when: not virt_net_remove | bool

- name: "NET: Remove the virtual network {{ virt_net_name }}"
  include_tasks: virt_net_remove.yml
  when: virt_net_remove | bool
