# Status of destroy and undefine doesn't change even when done
# Therefore the status settings
- block:
  - name: Destroy {{ virt_net_name }}
    virt_net:
      name: "{{ virt_net_name }}"
      command: destroy
    changed_when: true
  
  - name: Undefine {{ virt_net_name }}
    virt_net:
      name: "{{ virt_net_name }}"
      command: undefine
    changed_when: true

  rescue:
  - name: Info
    debug:
      msg: "{{ virt_net_name }} doesn't exists" 
