---
# defaults file for kelvinlnx.okd_vm_setup

gen_dir: ./generated
virt_registry_remove: False

# variable also used by virt_net_setup role
virt_net_name: okd
virt_net_domain: example.com

# The location of the ubuntu iso
os_iso: ~/Downloads/ubuntu-20.04.3-live-server-amd64.iso

myvm:
  host_ip: 88                             # only the host portion
  name: myreg
  fqdn: myreg.{{ virt_net_domain }}
  memory: 1024
  vcpu: 1
  disk:                                   # the following 3 lines used by create vm disk
    path: /var/lib/libvirt/images/myreg.qcow2
    size: 25G                             # 4.6.31 repo uses approx 6GB
  username: user
  password: password

user_pubkey_filename: "id_rsa.pub"        # file must be located in $(HOME)/.ssh/ directory
