---
# defaults file for kelvinlnx.okd_mirror

tmp_ca: "{{ root_ca | default(omit) }}"
my_pull_secret: "~/Downloads/pull-secret"

gen_dir: ./generated
cert_dir: "{{ gen_dir }}/private"

local_registry: "registry.example.net:5000"

registry:
  username: reguser
  password: regpass
  email: user@{{ local_registry | regex_search('[^:]*') }}
  secret: SecretUsedByRegistry
  auth: /srv/registry/auth
  certs: /srv/registry/certs
  data: /srv/registry/data
  port: "{{ registry_port | default('5000')}}"

tmp_cert:
  files:
    key: "{{ cert_dir }}/{{ local_registry | regex_search('[^:]*') }}.key"
    crt: "{{ cert_dir }}/{{ local_registry | regex_search('[^:]*') }}.crt"


# These are the registry mirroring informations needed. Refer to the
# docs at https://docs.openshift.com/container-platform/4.6/installing/installing-mirroring-installation-images.html#installing-mirroring-installation-images
# The listed defaults would work but it only mirrors OCP 4.6.310
ocp_release: 4.6.31                 # Choose from https://access.redhat.com/downloads/content/290/
local_repository: ocp4/openshift4
product_repo: openshift-release-dev               # for okd, set to "openshift"
release_name: 'ocp-release'                       # for okd, set to "okd"
architecture: x86_64

#rhcos_release: 4.6.1                # refer to https://mirror.openshift.com/pub/openshift-v4/dependencies/rhcos/

okd_client_tools: https://mirror.openshift.com/pub/openshift-v4/clients/oc/latest/linux/oc.tar.gz