---
# tasks file for kelvinlnx.okd_setup
- name: "NETWORK: Prep network and services"
  import_tasks: prep_network.yml

- name: "OKD: Prep OpenShift Configs"
  import_tasks: prep_okd.yml

- name: "INSTALL: Install OKD"
  import_tasks: install_okd.yml