---
# tasks file for kelvinlnx.okd_setup
- name: "NETWORK: Prep network"
  import_task: prep_network.yml

- name: "SERVICE: Prep services"
  import_task: prep_services.yml

- name: "OKD: Prep OpenShift Configs"
  import_task: prep_okd.yml

- name: "INSTALL: Install OKD"
  import_task: install_okd.yml