- block:
  - name: "NET: Reserved ip for myvm(add)"
    command: >-
      virsh net-update {{ virt_net_name }}
      add ip-dhcp-host
      "<host mac='{{ item.mac }}' name='{{ item.name }}' ip='{{ item.ip }}'/>"
      --live --config
    become: true
  rescue:
  - name: "NET: Reserved ip for myvm (modify)"
    command: >-
      virsh net-update {{ virt_net_name }}
      modify ip-dhcp-host
      "<host mac='{{ item.mac }}' name='{{ item.name }}' ip='{{ item.ip }}'/>"
      --live --config
    become: true
