---
# vars file for kelvinlnx.okd_setup
net_gw: "{{ (net_xml.get_xml | regex_search(\"ip.*address='([0-9\\.]*)'\",\"\\1\")) | first }}"
net_pt: "{{ net_gw | regex_search(\"^([0-9]{1,3}\\.){3}\") }}"

reserve_ip_list: >-
  {%- set results = []                                                    -%}
  {%- for value in node_list                                              -%}
  {%-   set node_item =
          { 'xpath':     '/network/ip/dhcp/host[@mac=\''+value.mac+'\']',
            'attribute': 'name',
            'value':     value.name }                                     -%}
  {%-   set _ = results.append(node_item)                                 -%}
  {%-   set node_item =
          { 'xpath':     '/network/ip/dhcp/host[@mac=\''+value.mac+'\']',
            'attribute': 'ip',
            'value':     value.ip }                                       -%}
  {%-   set _ = results.append(node_item)                                 -%}
  {%-   set node_item =
          { 'xpath':     '/network/dns/host[@ip=\''+value.ip+'\']/hostname',
            'value':     value.name }                                     -%}
  {%-   set _ = results.append(node_item)                                 -%}
  {%- endfor                                                              -%}
  {%-   set node_item =
          { 'xpath':     '/network/dns/host[@ip=\''+net_gw+'\']',
            'add_children': ['api', 'api-int'] }                          -%}
  {%-   set _ = results.append(node_item)                                 -%}
  {{ results }}