---
# vars file for kelvinlnx.okd_setup
net_gw: "{{ (a_result.get_xml | regex_search(\"ip.*address='([0-9\\.]*)'\",\"\\1\")) | first }}"
net_pt: "{{ net_gw | regex_search(\"^([0-9]{1,3}\\.){3}\") }}"

node_list: >-
  {%- set results = []                                                    -%}
  {%- set node_item=
      { 'name': 'bootstrap',
        'ip': net_pt + '9',
        'mac': (net_pt + '9') | hash('md5') |
         regex_replace("^(..)(..)(..).*", "52:54:00:\\1:\\2:\\3") }       -%}
  {%- set _ = results.append(node_item)                                   -%}
  {%- for value in range(0,master_nodes)                                  -%}
  {%-   set node_item=
        { 'name': 'master' + value|string,
    'ip': net_pt + '.' + (value+10)|string,
    'mac': (net_pt + value|string) | hash('md5') |
           regex_replace("^(..)(..)(..).*", "52:54:00:\\1:\\2:\\3") }     -%} 
  {%-   set _ = results.append(node_item)                                 -%}
  {%- endfor                                                              -%}
  {{ results }}

reserve_ip_list: >-
  {%- set results = []                                                    -%}
  {%- for value in node_list                                              -%}
  {%-   set node_item =
          { 'xpath':     '/network/ip/dhcp/host[@mac=\''+value.mac+'\']',
            'attribute': 'name',
            'value':     value.name }                                     -%}
  {%-   set _ = results.append(node_item)                                 -%}
  {%-   set node_item =
          { 'xpath': '/network/ip/dhcp/host[@mac=\''+value.mac+'\']',
            'attribute': 'ip',
            'value': value.ip }                                           -%}
  {%-   set _ = results.append(node_item)                                 -%}
  {%- endfor                                                              -%}
  {{ results }}
